language: node_js
node_js:
  - lts/*
install:
  - yarn install
script:
  - yarn vuepress-build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: vuepress/.vuepress/dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master